name:                aoc2021
version:             0.1.0.0
github:              "fersilva16/aoc2021"
license:             MIT
author:              "Fernando Silva"
maintainer:          "fernandonsilva16@gmail.com"
copyright:           "2021 Fernando Silva"
description:         Please see the README on GitHub at <https://github.com/fersilva16/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5
- split
- lens

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
